server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
    include-exception: true

  servlet:
    context-path: ${BASE_PATH:}

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    initialization-mode: always
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:auth_schema}?useTimezone=true&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:pass}

logging:
  level:
    root: info

token:
  secret: ${TOKEN_SECRET:secret}
  expiration:
    time:
      default: 60
      service: 43200
  source:
    header: ${HEADER_SOURCE_COOKIE:true}
    cookie: ${TOKEN_SOURCE_COOKIE:false}
    cookie-name: ${TOKEN_SOURCE_COOKIE_NAME:AUCC}
